site_name: AsBuiltReport.VMware.vSphere
repo_url: https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere
theme: readthedocs
pages:
- Home: index.md
- AsBuiltReport.VMware.vSphere Basics:
  - What is AsBuiltReport.VMware.vSphere: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
